import Head from 'next/head'
import fetchPageData from '../lib/fetchPageData'
import styles from '../styles/Home.module.css'
import AllComponents from '../components'

export default function Home({ data }) {
  const { homepage: { pageTitle, seo, components: pageComponents }} = data.data
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {pageComponents.map(component => {
          const RenderComponent = AllComponents[component.componentName]
          return <RenderComponent key={component.id} {...component.config} />
        })}


      </main>
    </div>
  )
}

export async function getStaticProps() {
  const pageData = await fetchPageData()

  return {
    props: {
      data: pageData
    }
  }
}